/**
 * Auto-generated main component exports
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-component-exports.ts
 * Version: 1.0.0
 * Generated: 2026-01-13T23:29:26.326Z
 */

// Re-export all components from categories
export * from './dealer';
export * from './ui';

// Component registry utilities
export * from './component-loader';
export type * from './registry-types';