/**
 * Auto-generated barrel exports for dealer components
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-component-exports.ts
 * Generated: 2026-01-13T23:29:26.325Z
 */

/** Mini shopping cart component */
export { default as MiniCart } from './dealer/MiniCart';

/** Mini cart trigger button */
export { default as MiniCartButton } from './dealer/MiniCartButton';
